# opruimen van een environment
pipenv --rm 

# opruimen van packages uit environment
pipenv run pip uninstall absl-py                              
pipenv run pip uninstall adal                                 
pipenv run pip uninstall aiohttp                              
pipenv run pip uninstall albumentations                       
pipenv run pip uninstall applicationinsights                  
pipenv run pip uninstall argon2-cffi                          
pipenv run pip uninstall async-timeout                        
pipenv run pip uninstall attrs                                
pipenv run pip uninstall azure-common                         
pipenv run pip uninstall azure-core                           
pipenv run pip uninstall azure-graphrbac                      
pipenv run pip uninstall azure-identity                       
pipenv run pip uninstall azure-mgmt-authorization             
pipenv run pip uninstall azure-mgmt-containerregistry         
pipenv run pip uninstall azure-mgmt-core                      
pipenv run pip uninstall azure-mgmt-keyvault                  
pipenv run pip uninstall azure-mgmt-resource                  
pipenv run pip uninstall azure-mgmt-storage                   
pipenv run pip uninstall azureml-automl-core                  
pipenv run pip uninstall azureml-core                         
pipenv run pip uninstall azureml-dataprep                     
pipenv run pip uninstall azureml-dataprep-native              
pipenv run pip uninstall azureml-dataprep-rslex               
pipenv run pip uninstall azureml-dataset-runtime              
pipenv run pip uninstall azureml-pipeline                     
pipenv run pip uninstall azureml-pipeline-core                
pipenv run pip uninstall azureml-pipeline-steps               
pipenv run pip uninstall azureml-sdk                          
pipenv run pip uninstall azureml-telemetry                    
pipenv run pip uninstall azureml-train-automl-client          
pipenv run pip uninstall azureml-train-core                   
pipenv run pip uninstall azureml-train-restclients-hyperdrive 
pipenv run pip uninstall backcall                             
pipenv run pip uninstall backports.tempfile                   
pipenv run pip uninstall backports.weakref                    
pipenv run pip uninstall beautifulsoup4                       
pipenv run pip uninstall bleach                               
pipenv run pip uninstall blis                                 
pipenv run pip uninstall boto3                                
pipenv run pip uninstall botocore                             
pipenv run pip uninstall Bottleneck                           
pipenv run pip uninstall bravado                              
pipenv run pip uninstall bravado-core                         
pipenv run pip uninstall cachetools                           
pipenv run pip uninstall captum                               
pipenv run pip uninstall catalogue                            
pipenv run pip uninstall catalyst                             
pipenv run pip uninstall certifi                              
pipenv run pip uninstall cffi                                 
pipenv run pip uninstall chardet                              
pipenv run pip uninstall charset-normalizer                   
pipenv run pip uninstall click                                
pipenv run pip uninstall cloudpickle                          
pipenv run pip uninstall configparser                         
pipenv run pip uninstall contextlib2                          
pipenv run pip uninstall cryptography                         
pipenv run pip uninstall cycler                               
pipenv run pip uninstall cymem                                
pipenv run pip uninstall debugpy                              
pipenv run pip uninstall decorator                            
pipenv run pip uninstall defusedxml                           
pipenv run pip uninstall distro                               
pipenv run pip uninstall docker                               
pipenv run pip uninstall docker-pycreds                       
pipenv run pip uninstall dotnetcore2                          
pipenv run pip uninstall entrypoints                          
pipenv run pip uninstall fastbook                             
pipenv run pip uninstall fastcore                             
pipenv run pip uninstall fastdownload                         
pipenv run pip uninstall fastprogress                         
pipenv run pip uninstall fastrelease                          
pipenv run pip uninstall filelock                             
pipenv run pip uninstall Flask                                
pipenv run pip uninstall fsspec                               
pipenv run pip uninstall fusepy                               
pipenv run pip uninstall future                               
pipenv run pip uninstall ghapi                                
pipenv run pip uninstall gitdb                                
pipenv run pip uninstall GitPython                            
pipenv run pip uninstall google-auth                          
pipenv run pip uninstall google-auth-oauthlib                 
pipenv run pip uninstall graphviz                             
pipenv run pip uninstall grpcio                               
pipenv run pip uninstall huggingface-hub                      
pipenv run pip uninstall hydra-slayer                         
pipenv run pip uninstall idna                                 
pipenv run pip uninstall imageio                              
pipenv run pip uninstall ipykernel                            
pipenv run pip uninstall ipython                              
pipenv run pip uninstall ipython-genutils                     
pipenv run pip uninstall ipywidgets                           
pipenv run pip uninstall isodate                              
pipenv run pip uninstall itsdangerous                         
pipenv run pip uninstall jedi                                 
pipenv run pip uninstall jeepney                              
pipenv run pip uninstall Jinja2                               
pipenv run pip uninstall jmespath                             
pipenv run pip uninstall joblib                               
pipenv run pip uninstall jsonpickle                           
pipenv run pip uninstall jsonref                              
pipenv run pip uninstall jsonschema                           
pipenv run pip uninstall jupyter                              
pipenv run pip uninstall jupyter-client                       
pipenv run pip uninstall jupyter-console                      
pipenv run pip uninstall jupyter-contrib-core                 
pipenv run pip uninstall jupyter-contrib-nbextensions         
pipenv run pip uninstall jupyter-core                         
pipenv run pip uninstall jupyter-highlight-selected-word      
pipenv run pip uninstall jupyter-latex-envs                   
pipenv run pip uninstall jupyter-nbextensions-configurator    
pipenv run pip uninstall jupyterlab-pygments                  
pipenv run pip uninstall jupyterlab-widgets                   
pipenv run pip uninstall kiwisolver                           
pipenv run pip uninstall kornia                               
pipenv run pip uninstall lxml                                 
pipenv run pip uninstall Markdown                             
pipenv run pip uninstall MarkupSafe                           
pipenv run pip uninstall matplotlib                           
pipenv run pip uninstall matplotlib-inline                    
pipenv run pip uninstall mistune                              
pipenv run pip uninstall monotonic                            
pipenv run pip uninstall msal                                 
pipenv run pip uninstall msal-extensions                      
pipenv run pip uninstall msgpack                              
pipenv run pip uninstall msrest                               
pipenv run pip uninstall msrestazure                          
pipenv run pip uninstall multidict                            
pipenv run pip uninstall murmurhash                           
pipenv run pip uninstall nbclient                             
pipenv run pip uninstall nbconvert                            
pipenv run pip uninstall nbdev                                
pipenv run pip uninstall nbformat                             
pipenv run pip uninstall ndg-httpsclient                      
pipenv run pip uninstall neptune-client                       
pipenv run pip uninstall nest-asyncio                         
pipenv run pip uninstall networkx                             
pipenv run pip uninstall ninja                                
pipenv run pip uninstall notebook                             
pipenv run pip uninstall numexpr                              
pipenv run pip uninstall numpy                                
pipenv run pip uninstall nvidia-ml-py3                        
pipenv run pip uninstall oauthlib                             
pipenv run pip uninstall opencv-python                        
pipenv run pip uninstall opencv-python-headless               
pipenv run pip uninstall packaging                            
pipenv run pip uninstall pandas                               
pipenv run pip uninstall pandocfilters                        
pipenv run pip uninstall parso                                
pipenv run pip uninstall pathspec                             
pipenv run pip uninstall pathtools                            
pipenv run pip uninstall pathy                                
pipenv run pip uninstall pexpect                              
pipenv run pip uninstall pickleshare                          
pipenv run pip uninstall Pillow                               
pipenv run pip uninstall pip                                  
pipenv run pip uninstall pkg-resources                        
pipenv run pip uninstall portalocker                          
pipenv run pip uninstall preshed                              
pipenv run pip uninstall prometheus-client                    
pipenv run pip uninstall promise                              
pipenv run pip uninstall prompt-toolkit                       
pipenv run pip uninstall protobuf                             
pipenv run pip uninstall psutil                               
pipenv run pip uninstall ptyprocess                           
pipenv run pip uninstall pyarrow                              
pipenv run pip uninstall pyasn1                               
pipenv run pip uninstall pyasn1-modules                       
pipenv run pip uninstall pycparser                            
pipenv run pip uninstall pydantic                             
pipenv run pip uninstall pyDeprecate                          
pipenv run pip uninstall pydicom                              
pipenv run pip uninstall Pygments                             
pipenv run pip uninstall PyJWT                                
pipenv run pip uninstall pyOpenSSL                            
pipenv run pip uninstall pyparsing                            
pipenv run pip uninstall pyrsistent                           
pipenv run pip uninstall python-dateutil                      
pipenv run pip uninstall pytorch-ignite                       
pipenv run pip uninstall pytorch-lightning                    
pipenv run pip uninstall pytz                                 
pipenv run pip uninstall PyWavelets                           
pipenv run pip uninstall PyYAML                               
pipenv run pip uninstall pyzmq                                
pipenv run pip uninstall qtconsole                            
pipenv run pip uninstall QtPy                                 
pipenv run pip uninstall qudida                               
pipenv run pip uninstall regex                                
pipenv run pip uninstall requests                             
pipenv run pip uninstall requests-oauthlib                    
pipenv run pip uninstall rsa                                  
pipenv run pip uninstall ruamel.yaml                          
pipenv run pip uninstall ruamel.yaml.clib                     
pipenv run pip uninstall s3transfer                           
pipenv run pip uninstall sacremoses                           
pipenv run pip uninstall scikit-image                         
pipenv run pip uninstall scikit-learn                         
pipenv run pip uninstall scipy                                
pipenv run pip uninstall SecretStorage                        
pipenv run pip uninstall Send2Trash                           
pipenv run pip uninstall sentencepiece                        
pipenv run pip uninstall sentry-sdk                           
pipenv run pip uninstall setuptools                           
pipenv run pip uninstall shortuuid                            
pipenv run pip uninstall simplejson                           
pipenv run pip uninstall six                                  
pipenv run pip uninstall smart-open                           
pipenv run pip uninstall smmap                                
pipenv run pip uninstall soupsieve                            
pipenv run pip uninstall spacy                                
pipenv run pip uninstall spacy-legacy                         
pipenv run pip uninstall srsly                                
pipenv run pip uninstall subprocess32                         
pipenv run pip uninstall swagger-spec-validator               
pipenv run pip uninstall tensorboard                          
pipenv run pip uninstall tensorboard-data-server              
pipenv run pip uninstall tensorboard-plugin-wit               
pipenv run pip uninstall tensorboardX                         
pipenv run pip uninstall termcolor                            
pipenv run pip uninstall terminado                            
pipenv run pip uninstall testpath                             
pipenv run pip uninstall thinc                                
pipenv run pip uninstall threadpoolctl                        
pipenv run pip uninstall tifffile                             
pipenv run pip uninstall tokenizers                           
pipenv run pip uninstall torch                                
pipenv run pip uninstall torchmetrics                         
pipenv run pip uninstall torchvision                          
pipenv run pip uninstall tornado                              
pipenv run pip uninstall tqdm                                 
pipenv run pip uninstall traitlets                            
pipenv run pip uninstall transformers                         
pipenv run pip uninstall typer                                
pipenv run pip uninstall typing-extensions                    
pipenv run pip uninstall urllib3                              
pipenv run pip uninstall wandb                                
pipenv run pip uninstall wasabi                               
pipenv run pip uninstall wcwidth                              
pipenv run pip uninstall webencodings                         
pipenv run pip uninstall websocket-client                     
pipenv run pip uninstall Werkzeug                             
pipenv run pip uninstall wheel                                
pipenv run pip uninstall widgetsnbextension                   
pipenv run pip uninstall yarl
pipenv run pip uninstall yaspin                               